baseURL: 'https://swecov.se/'
languageCode: 'en-us'

title: 'SWECOV'

menu:
  main:
    - name: 'Home'
      pageRef: '/'
      weight: 10
    - name: 'Research'
      pageRef: '/research'
      weight: 20
    - name: 'Workshops'
      pageRef: '/workshops'
      weight: 30
    - name: 'Join us'
      pageRef: '/participation'
      weight: 40
    - name: 'About SWECOV'
      pageRef: '/about_swecov'
      weight: 50

params:
  institution: 'Stockholm university'
  subtitle: 'Swedish COVID-19 Research'
  description: 'The Swedish Register-based Research Project on COVID-19 is a multidisciplinary research project using data-driven empirical methods to better understand the consequences of the pandemic.'
  brand_icon: 'virus-covid'
  favicon: 'virus-covid'
  primary_color: '#045E8B'
  secondary_color: '#ABD8ED'
  warning_color: '#FFCC4C'
  success_color: '#A0E68E'
  info_color: '#219EBC'
  danger_color: '#FB8500'
  project_filters:
    - 'status'
    - 'subject'
  project_search: true

module:
  imports:
    - path: github.com/adamaltmejd/research_project_theme

enableGitInfo: true

frontmatter:
  date:
    - date
    - :git
    - :fileModTime
  lastmod:
    - :git
    - :fileModTime
    - lastmod
    
outputs:
  section:
    - html
    - rss
    - json
